### ISSUE TITLE
Install failure on Fedora34

### ISSUE THREAD

**Issue by lack** [socratools/socranop#31]
I installed the alpha publish package from pip:

```
 jramsay  ~  $  pip install socranop                                                                                                                      
Defaulting to user installation because normal site-packages is not writeable                                                                                
Collecting socranop                                                                                                                                          
  Downloading socranop-0.4.92a1-py3-none-any.whl (71 kB)                                                                                                     
     |████████████████████████████████| 71 kB 5.0 MB/s                                                                                                       
Collecting pyusb                                                                                                                                             
  Downloading pyusb-1.2.1-py3-none-any.whl (58 kB)                                                                                                           
     |████████████████████████████████| 58 kB 9.7 MB/s                                                                                                       
Collecting pydbus                                                                                                                                            
  Downloading pydbus-0.6.0-py2.py3-none-any.whl (19 kB)                                                                                                      
Installing collected packages: pyusb, pydbus, socranop                                                                                                       
Successfully installed pydbus-0.6.0 pyusb-1.2.1 socranop-0.4.92a1
```

Then I ran the post-instal script:
```
 jramsay  ~  $  socranop-installtool --post-install
Using dirs HomeDirs(chroot=None, prefix='/home/jramsay/.local', datadir='/home/jramsay/.local/share', statedir='/home/jramsay/.config/socranop/state')
walk_through_data_files <socranop.installtool.BashCompletionInstallTool object at 0x7f61bf13a250> bash-completion                                            
res fullname data/bash-completion/socranop-session-service                                                                                                   
Adding file <socranop.installtool.BashCompletionInstallTool object at 0x7f61bf13a250> ResourceFile:/home/jramsay/.local/share/bash-completion/completions/soc
ranop-session-service:resource(data/bash-completion/socranop-session-service)                                                                                
res fullname data/bash-completion/socranop-gui                                                                                                               
Adding file <socranop.installtool.BashCompletionInstallTool object at 0x7f61bf13a250> ResourceFile:/home/jramsay/.local/share/bash-completion/completions/soc
ranop-gui:resource(data/bash-completion/socranop-gui)                                                                                                        
res fullname data/bash-completion/socranop-ctl                                                                                                               
Adding file <socranop.installtool.BashCompletionInstallTool object at 0x7f61bf13a250> ResourceFile:/home/jramsay/.local/share/bash-completion/completions/soc
ranop-ctl:resource(data/bash-completion/socranop-ctl)                                                                                                        
res fullname data/bash-completion/socranop-installtool                        
Adding file <socranop.installtool.BashCompletionInstallTool object at 0x7f61bf13a250> ResourceFile:/home/jramsay/.local/share/bash-completion/completions/soc
ranop-installtool:resource(data/bash-completion/socranop-installtool)                                                                                        
DBusInstallTool walk_through_data_files                                                                                                                      
walk_through_data_files <socranop.installtool.DBusInstallTool object at 0x7f61bf13a460> dbus-1                                                               
res fullname data/dbus-1/socranop.service                                                                                                                    
add_resource <socranop.installtool.DBusInstallTool object at 0x7f61bf13a460> data/dbus-1/socranop.service                                                    
Adding file <socranop.installtool.DBusInstallTool object at 0x7f61bf13a460> TemplateFile:/home/jramsay/.local/share/dbus-1/services/io.github.socratools.socr
anop.service:resource(data/dbus-1/socranop.service)
walk_through_data_files <socranop.installtool.ManpageInstallTool object at 0x7f61bfb70c10> man                                                               
res fullname data/man/socranop-session-service.1                              
Adding file <socranop.installtool.ManpageInstallTool object at 0x7f61bfb70c10> TemplateFile:/home/jramsay/.local/share/man/man1/socranop-session-service.1:re
source(data/man/socranop-session-service.1)                                                                                                                  
res fullname data/man/socranop-gui.1                                                                                                                         
Adding file <socranop.installtool.ManpageInstallTool object at 0x7f61bfb70c10> TemplateFile:/home/jramsay/.local/share/man/man1/socranop-gui.1:resource(data/
man/socranop-gui.1)                                                                                                                                          
res fullname data/man/socranop-ctl.1                                          
Adding file <socranop.installtool.ManpageInstallTool object at 0x7f61bfb70c10> TemplateFile:/home/jramsay/.local/share/man/man1/socranop-ctl.1:resource(data/
man/socranop-ctl.1)                                                           
walk_through_data_files <socranop.installtool.XDGDesktopInstallTool object at 0x7f61bf152310> xdg                                                           
res fullname data/xdg/io.github.socratools.socranop.desktop                                                                                                  
Adding file <socranop.installtool.XDGDesktopInstallTool object at 0x7f61bf152310> TemplateFile:/home/jramsay/.local/share/applications/io.github.socratools.s
ocranop.desktop:resource(data/xdg/io.github.socratools.socranop.desktop)                                                                                     
res fullname data/xdg/io.github.socratools.socranop.24.png                                                                                                   
Adding file <socranop.installtool.XDGDesktopInstallTool object at 0x7f61bf152310> ResourceFile:/home/jramsay/.local/share/icons/hicolor/24x24/apps/io.github.
socratools.socranop.png:resource(data/xdg/io.github.socratools.socranop.24.png)                                                                              
res fullname data/xdg/io.github.socratools.socranop.64.png
Adding file <socranop.installtool.XDGDesktopInstallTool object at 0x7f61bf152310> ResourceFile:/home/jramsay/.local/share/icons/hicolor/64x64/apps/io.github.
socratools.socranop.png:resource(data/xdg/io.github.socratools.socranop.64.png)
res fullname data/xdg/io.github.socratools.socranop.48.png
Adding file <socranop.installtool.XDGDesktopInstallTool object at 0x7f61bf152310> ResourceFile:/home/jramsay/.local/share/icons/hicolor/48x48/apps/io.github.
socratools.socranop.png:resource(data/xdg/io.github.socratools.socranop.48.png)
res fullname data/xdg/io.github.socratools.socranop.192.png
Adding file <socranop.installtool.XDGDesktopInstallTool object at 0x7f61bf152310> ResourceFile:/home/jramsay/.local/share/icons/hicolor/192x192/apps/io.githu
b.socratools.socranop.png:resource(data/xdg/io.github.socratools.socranop.192.png)
res fullname data/xdg/io.github.socratools.socranop.svg
Adding file <socranop.installtool.XDGDesktopInstallTool object at 0x7f61bf152310> ResourceFile:/home/jramsay/.local/share/icons/hicolor/scalable/apps/io.gith
ub.socratools.socranop.svg:resource(data/xdg/io.github.socratools.socranop.svg)
res fullname data/xdg/io.github.socratools.socranop.128.png
Adding file <socranop.installtool.XDGDesktopInstallTool object at 0x7f61bf152310> ResourceFile:/home/jramsay/.local/share/icons/hicolor/128x128/apps/io.githu
b.socratools.socranop.png:resource(data/xdg/io.github.socratools.socranop.128.png)
res fullname data/xdg/io.github.socratools.socranop.256.png
Adding file <socranop.installtool.XDGDesktopInstallTool object at 0x7f61bf152310> ResourceFile:/home/jramsay/.local/share/icons/hicolor/256x256/apps/io.githu
b.socratools.socranop.png:resource(data/xdg/io.github.socratools.socranop.256.png)
res fullname data/xdg/io.github.socratools.socranop.16.png
Adding file <socranop.installtool.XDGDesktopInstallTool object at 0x7f61bf152310> ResourceFile:/home/jramsay/.local/share/icons/hicolor/16x16/apps/io.github.
socratools.socranop.png:resource(data/xdg/io.github.socratools.socranop.16.png)
res fullname data/xdg/io.github.socratools.socranop.96.png
Adding file <socranop.installtool.XDGDesktopInstallTool object at 0x7f61bf152310> ResourceFile:/home/jramsay/.local/share/icons/hicolor/96x96/apps/io.github.
socratools.socranop.png:resource(data/xdg/io.github.socratools.socranop.96.png)
res fullname data/xdg/io.github.socratools.socranop.32.png
Adding file <socranop.installtool.XDGDesktopInstallTool object at 0x7f61bf152310> ResourceFile:/home/jramsay/.local/share/icons/hicolor/32x32/apps/io.github.
socratools.socranop.png:resource(data/xdg/io.github.socratools.socranop.32.png)
Adding file <socranop.installtool.UdevRulesInstallTool object at 0x7f61bf152400> StringToFile:/etc/udev/rules.d/70-socranop.rules
Trying to import gi.repository.GLib
Trying to require module Gtk version 3.0
Trying to import gi.repository.Gtk
Trying to import gi.repository.Gio
Trying to require module GUdev version 1.0
Trying to import gi.repository.GUdev
Checking installed packages: Good.
  [inst] /home/jramsay/.local/share/bash-completion/completions/socranop-ctl
  [inst] /home/jramsay/.local/share/bash-completion/completions/socranop-gui
  [inst] /home/jramsay/.local/share/bash-completion/completions/socranop-installtool
  [inst] /home/jramsay/.local/share/bash-completion/completions/socranop-session-service
Old D-Bus service not running
  [inst] /home/jramsay/.local/share/dbus-1/services/io.github.socratools.socranop.service
Starting D-Bus service io.github.socratools.socranop as a test...
Installtool version: 0.4.92
Retrying 5...
Retrying 4...
Retrying 3...
Retrying 2...
Retrying 1...
Traceback (most recent call last):
  File "/home/jramsay/.local/bin/socranop-installtool", line 8, in <module>
    sys.exit(main())
  File "/home/jramsay/.local/lib/python3.9/site-packages/socranop/installtool.py", line 890, in main
    everything.post_install()
  File "/home/jramsay/.local/lib/python3.9/site-packages/socranop/installtool.py", line 813, in post_install
    thing.post_install()
  File "/home/jramsay/.local/lib/python3.9/site-packages/socranop/installtool.py", line 554, in post_install
    dbus_service.StartServiceByName(const.BUSNAME, 0)
  File "/home/jramsay/.local/lib/python3.9/site-packages/pydbus/proxy_method.py", line 72, in __call__
    ret = instance._bus.con.call_sync(
gi.repository.GLib.Error: g-dbus-error-quark: GDBus.Error:org.freedesktop.DBus.Error.ServiceUnknown: The name is not activatable (2)
```

Not only did the dbus service not start, but I also don't see the .desktop file or the icons where they're supposed to be:

```
 jramsay  ~  $  ls .local/share/applications/
chrome-aapocclcgogkmnckokdopfmhonfmgoek-Profile_1.desktop  chrome-mdpkiolbdkhdjpekfbkbmhigcaggjagi-Profile_1.desktop
chrome-aghbiahbpaijignceidepookljebhfak-Default.desktop    chrome-nmmhkkegccagdldgiimedpiccmgmieda-Default.desktop
chrome-agimnkijcaahngcdmfeangaknmldooml-Profile_1.desktop  chrome-nmmhkkegccagdldgiimedpiccmgmieda-Profile_1.desktop
chrome-aohghmighlieiainnegkcijnfilokake-Profile_1.desktop  chrome-nmmhkkegccagdldgiimedpiccmgmieda-Profile_2.desktop
chrome-apdfllckaahabafndbhieahigkjlhalf-Default.desktop    chrome-nmmhkkegccagdldgiimedpiccmgmieda-Profile_3.desktop
chrome-apdfllckaahabafndbhieahigkjlhalf-Profile_1.desktop  chrome-pjkljhegncpnkpknbcohdijeoejaedia-Default.desktop
chrome-cinhimbnkkaeohfgghhklpknlkffjgod-Profile_1.desktop  chrome-pjkljhegncpnkpknbcohdijeoejaedia-Profile_1.desktop
chrome-fahmaaghhglfmonjliepjlchgpgfmobi-Profile_4.desktop  install4j_j162e7-FTBApp.desktop
chrome-felcaaldnbdncclmgdcncolpebgiejap-Profile_1.desktop  mimeapps.list
chrome-hmjkmjkepdijhoojdojkdfohbdgmmhki-Profile_1.desktop  mimeinfo.cache
chrome-hpfldicfbfomlpcikngkocigghgafkph-Profile_1.desktop  Webcamoid.desktop
chrome-mdpkiolbdkhdjpekfbkbmhigcaggjagi-Default.desktop
 jramsay  ~  $  ls .local/share/icons/hicolor/128x128/apps/
chrome-aapocclcgogkmnckokdopfmhonfmgoek-Profile_1.png  chrome-fhbjgbiflinjbdggehcddcbncdddomop-Profile_1.png
chrome-aghbiahbpaijignceidepookljebhfak-Default.png    chrome-hmjkmjkepdijhoojdojkdfohbdgmmhki-Profile_1.png
chrome-agimnkijcaahngcdmfeangaknmldooml-Profile_1.png  chrome-hpfldicfbfomlpcikngkocigghgafkph-Profile_1.png
chrome-aohghmighlieiainnegkcijnfilokake-Profile_1.png  chrome-mdpkiolbdkhdjpekfbkbmhigcaggjagi-Default.png
chrome-apdfllckaahabafndbhieahigkjlhalf-Default.png    chrome-mdpkiolbdkhdjpekfbkbmhigcaggjagi-Profile_1.png
chrome-apdfllckaahabafndbhieahigkjlhalf-Profile_1.png  chrome-nmmhkkegccagdldgiimedpiccmgmieda-Default.png
chrome-chfbpgnooceecdoohagngmjnndbbaeip-Default.png    chrome-nmmhkkegccagdldgiimedpiccmgmieda-Profile_1.png
chrome-chfbpgnooceecdoohagngmjnndbbaeip-Profile_1.png  chrome-nmmhkkegccagdldgiimedpiccmgmieda-Profile_2.png
chrome-cinhimbnkkaeohfgghhklpknlkffjgod-Profile_1.png  chrome-nmmhkkegccagdldgiimedpiccmgmieda-Profile_3.png
chrome-fahmaaghhglfmonjliepjlchgpgfmobi-Profile_1.png  chrome-pjkljhegncpnkpknbcohdijeoejaedia-Default.png
chrome-fahmaaghhglfmonjliepjlchgpgfmobi-Profile_4.png  chrome-pjkljhegncpnkpknbcohdijeoejaedia-Profile_1.png
chrome-felcaaldnbdncclmgdcncolpebgiejap-Profile_1.png  webcamoid.png
```

**Comment by ndim** [comment]
The sequence in which `socranop-installtool` handles its workload is: CheckDependencies, BashCompletionInstallTool, DBusInstallTool, ManpageInstallTool, XDGDesktopInstallTool, UdevRulesInstallTool. If one tool fails and aborts the program, the subsequent tools will not execute. This explains the failure to install e.g. the `.desktop` and icon files.

So the remaining question is: Why does `starting` the D-Bus service fail? I do not have an answer yet, but a few potentially useful facts.

In my tests, this appears to be related to the kind of shell/session/user the `socranop-installtool` is running in. I have tested with two non-root users here, user1 and user2.

user1 is first logged into a graphical Gnome session, and then also logged into a virtual console. Both from a `gnome-terminal` within the Gnome session, and from the virtual console, user1 can run `socranop-installtool --post-install` successfully, and `socranop-ctl --list` will connect to the D-Bus service and implicitly launch the service.

user2 is first logged into a virtual console. While user2 can explicitly run `socranop-session-service` on that virtual console, the D-Bus activation does not work. If user2 is then logged into a graphical Gnome session, the D-Bus activation does not magically start working. Neither from the virtual console shell nor from a gnome-terminal inside the Gnome session.

Both users have a `/usr/lib/systemd/systemd --user` process running, which in turn has a `/usr/bin/dbus-broker-launch --scope user` and which in turn has a `dbus-broker --log 4 --controller 10 --machine-id ... --max-bytes ... --max-fds ... --max-matches ...` running, so there is no difference to be seen here. No noticeable difference here.

I cannot think of why there should be a difference between user1 and user2.

**Comment by lack** [comment]
Are the directories we select for installation different for the 2 users because of different environment variables, maybe?

**Comment by lack** [comment]
Aha, I may have a line on the root cause:

If the `~/.local/share/dbus-1/services` directory doesn't exist when the dbus-broker-launch process starts up, it doesn't seem to notice if it is created and new services created inside.  On the other hand, if the directory exists before dbus-broker-launch starts, it properly registers any additions or removals from that directory.

**Comment by lack** [comment]
On my system, same session as the one that failed in the original post, running `systemctl --user reload dbus-broker.service` and then re-running `socranop-installtool --post-install` succeed!

**Comment by lack** [comment]
In fact, it looks like systemctl reload actually does

```
busctl --user call org.freedesktop.DBus /org/freedesktop/DBus org.freedesktop.DBus ReloadConfig
```

So perhaps we can just call that dbus method directly as part of installing the service before trying to activate it!

**Comment by ndim** [comment]
> Aha, I may have a line on the root cause:
> 
> If the `~/.local/share/dbus-1/services` directory doesn't exist when the dbus-broker-launch process starts up, it doesn't seem to notice if it is created and new services created inside. On the other hand, if the directory exists before dbus-broker-launch starts, it properly registers any additions or removals from that directory.

This sounds like a bug in dbus-broker-launch to me.

**Comment by lack** [comment]
> > Aha, I may have a line on the root cause:
> > If the `~/.local/share/dbus-1/services` directory doesn't exist when the dbus-broker-launch process starts up, it doesn't seem to notice if it is created and new services created inside. On the other hand, if the directory exists before dbus-broker-launch starts, it properly registers any additions or removals from that directory.
> 
> This sounds like a bug in dbus-broker-launch to me.

Probably.  The original dbus implementation (on ubuntu) doesn't see to suffer from the same issue.  It's hard to set up inotify correctly if you want to monitor files in a directory that doesn't exist when you start up, but it's probably worth reporting upstream.  I'll try to do that ... soon.
