### ISSUE TITLE
socranop.dirs module breaks on NixOS

### ISSUE THREAD

**Issue by ndim** [socratools/socranop#77]
A NixOS installation looks so much not like a FHS system that `socranop-installtool package-build-install` breaks when running `socranop.dirs.init_dirs(chroot=...)`.

At this time, the `socranop.dirs` package and thus all of `socranop` only works on common FHS systems.

```
…
pwd=/build/socranop
out=/nix/store/cj3i4b5jlc96pvdj0dp0ksg8h6xcxdxk-socranop-0.0.2
args after parse_args: Namespace(verbose=False, dry_run=False, command='package-build-install', chroot=PosixPath('/nix/store/cj3i4b5jlc96pvdj0dp0ksg8h6xcxdxk-socranop-0.0.2'))
Traceback (most recent call last):
  File "/nix/store/cj3i4b5jlc96pvdj0dp0ksg8h6xcxdxk-socranop-0.0.2/bin/socranop-installtool", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/nix/store/cj3i4b5jlc96pvdj0dp0ksg8h6xcxdxk-socranop-0.0.2/lib/python3.11/site-packages/socranop/installtool.py", line 1252, in main
    args = parse_argv(argv)
           ^^^^^^^^^^^^^^^^
  File "/nix/store/cj3i4b5jlc96pvdj0dp0ksg8h6xcxdxk-socranop-0.0.2/lib/python3.11/site-packages/socranop/installtool.py", line 1216, in parse_argv
    dirs = init_dirs(chroot=args.chroot)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/nix/store/cj3i4b5jlc96pvdj0dp0ksg8h6xcxdxk-socranop-0.0.2/lib/python3.11/site-packages/socranop/dirs.py", line 247, in init_dirs
    raise UnsupportedInstall(
socranop.dirs.UnsupportedInstall: exename='/nix/store/cj3i4b5jlc96pvdj0dp0ksg8h6xcxdxk-socranop-0.0.2/bin/socranop-installtool', chroot=PosixPath('/nix/store/cj3i4b5jlc96pvdj0dp0ksg8h6xcxdxk-socranop-0.0.2')
```

**Comment by ndim** [comment]
@pakettiale I want to fix this in `socranop.dirs`. There is no need to invent elaborate workarounds on the nix derivation side.

**Comment by ndim** [comment]
This might be as easy as just supporting the install location prefix `/` in addition to `/usr` and `/usr/local` and `$HOME/.local`.

**Comment by ndim** [comment]
This probably requires `socranop.dirs` to support installs to arbitrary prefixes like e.g. `/nix/store/8hx2p33jn7hmkmxaq2mn76kwwlzcfrxw-socranop-0.0.3`, and `socranop-installtool package-build-install` to have a `--prefix` argument.

That `--prefix` argument might disable the normal mapping of install location to well known locations for udev, D-Bus, etc files and activate a different mapping. In any case, those config files should end up in places where NixOS needs them.

(I am a NixOS and nix newb, so I might be wrong about NixOS and nix)

**Comment by ndim** [comment]
Would `--useprefix` be better than `--force-prefix`?
